# Use official Node.js image
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json first
COPY package.json package-lock.json ./

ENV NODE_ENV development

# Install dependencies
RUN npm install
RUN npm install -g nodemon

# Copy the rest of the app
COPY . .

EXPOSE 4000

# Start the server
CMD ["npm", "run", "dev"]